version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout

      - run: 
          name: Check flutter installation
          command: flutter doctor

      - run: 
          name: Test the app
          command: flutter test
          